google_api:
    elevation_base_url: 'https://maps.googleapis.com/maps/api/elevation/json?locations='

ingestion_settings:
  staging_db_location: '../data/staging.db'
  data_directory: '../data'

  database_model:
    trips_table: trips
    trips_path: trips
    trip_columns:
      - system_trip_id
      - system_id
      - from_station_id
      - to_station_id
      - time_start
      - time_stop
      - bike_name
      - duration_s
      - usertype
      - gender
      - birthyear

    stations_table: stations
    station_file_name: stations.csv
    station_columns:
      - system_id
      - short_name
      - name
      - latitude
      - longitude
      - date_installed
      - capacity_initial
      - date_modified
      - capacity
      - date_decommissioned

  datasources:
    pronto:
      system_id: pronto

      station_fields:
        station_id: short_name
        lat: latitude
        long: longitude
        install_date: date_installed
        install_dockcount: capacity_initial
        modification_date: date_modified
        current_dockcount: capacity
        decommission_date: date_decommissioned

      trip_fields:
        trip_id: system_trip_id
        starttime: time_start
        stoptime: time_stop
        bikeid: bike_name
        tripduration: duration_s
        from_station_id: from_station_id
        to_station_id: to_station_id

      user_type_mapping:
        pass: Short-Term Pass Holder
        member: Member

    healthyride:
      system_id: healthyride

      station_fields:
        StationNum: short_name
        StationName: name
        RackQnty: capacity
        Latitude: latitude
        Longitude: longitude

      trip_fields:
        "Trip id": system_trip_id
        Starttime: time_start
        Stoptime: time_stop
        Bikeid: bike_name
        Tripduration: duration_s
        'From station id': from_station_id
        'To station id': to_station_id
        Usertype: usertype

    divvy:
      system_id: divvy

      station_fields:
        id: short_name
        dpcapacity: capacity
        online_date: date_installed

      trip_fields:
        trip_id: system_trip_id
        starttime: time_start
        stoptime: time_stop
        bikeid: bike_name
        tripduration: duration_s
        from_station_id: from_station_id
        to_station_id: to_station_id
        birthday: birthyear

      user_type_mappings:
        pass: Customer
        member: Subscriber

    bike_chattanooga:
      system_id: bike_chattanooga

      station_fields:
        StationID: short_name
        Address: name
        Latitude: latitude
        Longitude: longitude

      trip_fields:
        MemberType: usertype
        TripDurationSec: duration_s
        BikeID: bike_name
        StartDateTime: time_start
        StartStationID: from_station_id
        EndDateTime: time_stop
        EndStationID: to_station_id

      user_type_mappings:
        pass: Customer
        member: Subscriber

    babs:
      system_id: babs

      station_fields:
        station_id: short_name
        lat: latitude
        long: longitude
        dockcount: capacity
        installation: date_installed

      trip_fields:
        Duration: duration_s
        Start Date: time_start
        Start Terminal: from_station_id
        End Date: time_stop
        End Terminal: to_station_id
        'Bike #': bike_name
        Subscription Type: usertype
        Subscriber Type: usertype

      user_type_mappings:
        pass: Customer
        member: Subscriber