log: '../trips_ingestion.log'
bad_data_log: '../bad_trip_data.log'

google_api:
    elevation_base_url: 'https://maps.googleapis.com/maps/api/elevation/json?locations='

ingestion_settings:
  staging_db_location: '../data/staging.db'
  data_directory: '../data'
  station_file_name: stations.csv
  trips_directory: trips


# Lists data sources and field mappings.
#
# Caution: station headers are mapped FROM standard names TO data file names but
# trip mapping are FROM data file names TO standard names. See ingests_trips.py.

datasources:
  pronto:
    system_id: pronto
    weather_station: 'GHCND:USW00094290'

    station_fields:
      station_id: short_name
      lat: latitude
      long: longitude
      install_date: date_installed
      install_dockcount: capacity_initial
      modification_date: date_modified
      current_dockcount: capacity
      decommission_date: date_decommissioned

    trip_fields:
      trip_id: system_trip_id
      starttime: time_start
      stoptime: time_stop
      bikeid: bike_name
      tripduration: duration_s
      from_station_id: start_station_short_name
      to_station_id: end_station_short_name
      gender: customer_gender
      usertype: customer_type
      birthyear: customer_birthyear

    user_type_mapping:
      Short-Term Pass Holder: customer
      Member: subscriber

  healthyride:
    system_id: healthyride
    weather_station: 'GHCND:USW00014762'

    station_fields:
      'Station #': short_name
      Station Name: name
      '# of Racks': capacity
      Latitude: latitude
      Longitude: longitude
      StationNum: short_name
      StationName: name
      RackQnty: capacity

    trip_fields:
      "Trip id": system_trip_id
      Starttime: time_start
      Stoptime: time_stop
      Bikeid: bike_name
      Tripduration: duration_s
      From station id: start_station_short_name
      To station id: end_station_short_name
      Usertype: customer_type

  divvy:
    system_id: divvy
    weather_station: 'GHCND:USW00014819'

    station_fields:
      id: short_name
      dpcapacity: capacity
      online_date: date_installed

    trip_fields:
      trip_id: system_trip_id
      '"trip_id"': system_trip_id
      starttime: time_start
      '"starttime"': time_start
      stoptime: time_stop
      '"stoptime"': time_stop
      bikeid: bike_name
      '"bikeid"': bike_name
      tripduration: duration_s
      '"tripduration"': duration_s
      from_station_name: start_station_name
      '"from_station_name"': start_station_name
      to_station_name: end_station_name
      '"to_station_name"': end_station_name
      from_station_id: start_station_short_name
      to_station_id: end_station_short_name
      birthday: customer_birthyear
      birthyear: customer_birthyear
      usertype: customer_type
      '"usertype"': customer_type
      gender: customer_gender
      '"gender"': customer_gender

  bike_chattanooga:
    system_id: bike_chattanooga
    weather_station: 'GHCND:USW00013882'

    station_fields:
      StationID: short_name
      Address: name
      Latitude: latitude
      Longitude: longitude

    trip_fields:
      MemberType: usertype
      TripDurationSec: duration_s
      BikeID: bike_name
      StartDateTime: time_start
      StartStationID: start_station_short_name
      EndDateTime: time_stop
      EndStationID: end_station_short_name
      'MemberType': customer_type

  babs:
    system_id: babs
    weather_station: 'GHCND:USW00023234'

    station_fields:
      station_id: short_name
      lat: latitude
      long: longitude
      dockcount: capacity
      installation: date_installed

    trip_fields:
      Duration: duration_s
      Start Date: time_start
      Start Terminal: start_station_short_name
      End Date: time_stop
      End Terminal: end_station_short_name
      'Bike #': bike_name
      Subscription Type: customer_type
      Subscriber Type: customer_type

  indego:
    system_id: indego

    station_fields:
      Station ID: station_short_name
      Station Name: station_name
      Go live date: date_installed

    trip_fields:
      duration: duration_s
      start_time: time_start
      end_time: time_stop
      start_station_id: start_station_short_name
      end_station_id: end_station_short_name
      start_lat: start_station_latitude
      start_lon: start_station_longitude
      end_lat: end_station_latitude
      end_lon: end_station_longitude
      bike_id: bike_name
      passholder_type: customer_type



weather:
  weather_data_dir: '../weather'
  weather_mappings:
    precipitation_in: PRCP
    snow_in: SNOW
    temp_min_f: TMIN
    temp_max_f: TMAX
    wind_mph: AWND